theme = "nodept"
baseURL = "https://ritualdust.com/"
languageCode = "en-ca"
title = "Ritual dust"
author = "Lizbeth Poirier"
copyright = "Copyright © 2008–2024, Lizbeth Poirier-Morissette; all rights reserved."
DefaultContentLanguage = "en"

[params]
image = "/img/preview.png"
desc = "Portfolio, digital garden and recipe blog of designer, illustrator and goth druid Lizbeth Poirier. Write your won folklore."

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "artwork"
    name = "Artwork"
    url = "/works/"
    weight = 2
  [[menu.main]]
    identifier = "music"
    name = "Music"
    url = "/music/"
    weight = 3
  [[menu.main]]
    identifier = "tattoo"
    name = "Tattoo"
    url = "/tattoo/"
    weight = 4
  [[menu.main]]
    identifier = "shop"
    name = "Shop"
    url = "/shop/"
    weight = 5
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 6

[markup]

  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[frontmatter]

  date = ["date", "publishDate", "lastmod"]
  lastmod = ["lastmod", ":fileModTime", ":default"]
  publishDate = ["publishDate", "date"]
  expiryDate = ["expiryDate"]
