
theme = "nodept"
baseURL = "https://ritualdust.com/"
languageCode = "en-ca"
title = "Ritual dust"
author = "Lizbeth Poirier"
copyright = "Copyright © 2008–2024, Lizbeth Poirier-Morissette; all rights reserved."
DefaultContentLanguage = "en"

[params]
image = "/img/preview.png"
desc = "Portfolio, digital garden and recipe blog of designer, illustrator and goth druid Lizbeth Poirier. Write your won folklore."

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "artwork"
    name = "Artwork"
    url = "/works/"
    weight = 2
  [[menu.main]]
    identifier = "music"
    name = "Music"
    url = "/music/"
    weight = 3
  [[menu.main]]
    identifier = "tattoo"
    name = "Tattoo"
    url = "/tattoo/"
    weight = 4
  [[menu.main]]
    identifier = "shop"
    name = "Shop"
    url = "/shop/"
    weight = 5
  [[menu.main]]
    identifier = "commissions"
    name = "Commissions"
    url = "/works/commissions/"
    weight = 6
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 7
    
  [[menu.footer1]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.footer1]]
    identifier = "artwork"
    name = "Artwork"
    url = "/works/"
    weight = 2
  [[menu.footer1]]
    identifier = "music"
    name = "Music"
    url = "/music/"
    weight = 3
  [[menu.footer1]]
    identifier = "tattoo"
    name = "Tattoo"
    url = "/tattoo/"
    weight = 4
  [[menu.footer1]]
    identifier = "craft"
    name = "Craft"
    url = "/craft/"
    weight = 5
  [[menu.footer1]]
    identifier = "folklore"
    name = "Folklore"
    url = "/folklore/"
    weight = 5
  [[menu.footer1]]
    identifier = "food"
    name = "Food"
    url = "/food/"
    weight = 5
  [[menu.footer1]]
    identifier = "play"
    name = "Play"
    url = "/play/"
    weight = 6
  [[menu.footer1]]
    identifier = "shop"
    name = "Shop"
    url = "/shop/"
    weight = 7
  [[menu.footer1]]
    identifier = "commissions"
    name = "Commissions"
    url = "/works/commissions/"
    weight = 6  
  [[menu.footer1]]
    identifier = "printclub"
    name = "Print Club"
    url = "/works/print-club/"
    weight = 7
  [[menu.footer1]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 8
    
  [[menu.footer2]]
    identifier = "website"
    name = "This website"
    url = "/about/this-website/"
    weight = 1
  [[menu.footer2]]
    identifier = "tree"
    name = "Tree"
    url = "/tree/"
    weight = 2
  [[menu.footer2]]
    identifier = "timeline"
    name = "Timeline"
    url = "/timeline/"
    weight = 3
  [[menu.footer2]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 4
  [[menu.footer2]]
    identifier = "media"
    name = "Media"
    url = "/about/"
    weight = 5
  [[menu.footer2]]
    identifier = "notes"
    name = "Notes"
    url = "/notes/"
    weight = 6
  [[menu.footer2]]
    identifier = "journal"
    name = "Journal"
    url = "/journal/"
    weight = 7




[markup]

  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[frontmatter]

  date = ["date", "publishDate", "lastmod"]
  lastmod = ["lastmod", ":fileModTime", ":default"]
  publishDate = ["publishDate", "date"]
  expiryDate = ["expiryDate"]
